name: Deploy to ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Update AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          sudo pip3 install --upgrade awscli

      - name: Debug AWS CLI Configuration
        run: aws configure list

      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_REGISTRY_URL }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Build, test, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: clo835-week3-1
          IMAGE_TAG: v0.1
        run: |
          cd Chapter02/kubia/
          ls -ltra
          # Docker build command
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Unit test
          docker run -d -p 80:8080 --name nodeapp $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker ps
          echo "Pause for 10 seconds to let the container start"
          sleep 10
          curl localhost -vvv
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
